<?php


return [
    'Super Admin' => [
        'superadmin',
    ],
    'Admin Frota' => [
        'manage-reservation',
        'view-reservation',
        'delete-reservation',
        'report-reservation',
        'edit-reservation',
        'manage-vehicle',
        'view-vehicle',
        'create-vehicle',
        'edit-vehicle',
        'delete-vehicle',
        'manage-user',
        'view-user',
        'create-user',
        'edit-user',
        'delete-user',
        'manage-city',
        'view-city',
        'create-city',
        'edit-city',
        'delete-city',
        'manage-branch',
        'view-branch',
        'create-branch',
        'edit-branch',
        'delete-branch',
        'manage-branch-vehicle',
        'view-branch-vehicle',
        'create-branch-vehicle',
        'edit-branch-vehicle',
        'delete-branch-vehicle',
        'manage-debit',
        'view-debit',
        'create-debit',
        'edit-debit',
        'delete-debit',

    ],
    'Gestor' => [
        'manage-reservation',
        'view-reservation',
        'edit-reservation',
        'report-reservation',
        'manage-vehicle',
        'view-vehicle',
        'edit-vehicle',
        'manage-user',
        'view-user',
        'create-user',
        'manage-city',
        'view-city',
        'create-city',
        'manage-branch',
        'view-branch',
        'create-branch',
        'edit-branch',
        'manage-branch-vehicle',
        'view-branch-vehicle',
        'edit-branch-vehicle',
        'manage-debit',
        'view-debit',
        'create-debit',
        'edit-debit',
        'delete-debit',
    ],
    'Operador' => [],
    'Motorista' => [
        'create-reservation',
        'view-reservation',
        'checking-reservation',
        'manage-reservation',
        'manage-debit',
        'view-debit',
        'create-debit',
        // 'report-reservation',
    ],
];